/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn sdk_init(log_type: ::std::os::raw::c_uint) -> bool;
}
unsafe extern "C" {
    pub fn get_sdk_version() -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn sdk_release() -> bool;
}
